# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for iosApp
  pod 'RevenueCat', '5.19.0'
  pod 'RevenueCatUI', '5.19.0'
  pod 'PurchasesHybridCommon', git: 'https://github.com/revenuecat/purchases-hybrid-common', branch: 'chore/public-initialiser'
  pod 'PurchasesHybridCommonUI', git: 'https://github.com/revenuecat/purchases-hybrid-common', branch: 'chore/public-initialiser'
end
