# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for iosApp
  pod 'PurchasesHybridCommon', '15.0.0'
  pod 'PurchasesHybridCommonUI', '15.0.0'
end
